### ISSUE TITLE
subtree-owners can't create new namespaces

### ISSUE THREAD

**Issue by ljpearlman** [informatics-isi-edu/hatrac#52]
I'm not sure whether this is a bug in hatrac or in the [docs](http://docs.derivacloud.org/hatrac/REST-API.html#access-control-list-sub-resources), but earlier today this command failed for Animesh, despite the fact that he's in the isrd-testers group (https://auth.globus.org/1b55dedd-adf9-4c97-ba5c-e5be97a36dbd), which has subtree-owner permission on /hatrac/resources on dev.rebuildingakidney.org:

```
128.9.180.194 - https://auth.globus.org/1b55dedd-adf9-4c97-ba5c-e5be97a36dbd [27/Jun/2019:15:10:00 -0700] "POST /hatrac/resources/publication/2019/79f8d98c69415bdae8b3df1931c0866a;upload?parents=true HTTP/2.0" 403 39
```

A similar request succeded for me, and Animesh was able to do the same (presumably because the /publication/2019 namespace had been created.

```
128.9.136.72 - https://auth.globus.org/a4e03698-d274-11e5-9a48-8b6f49eb5587 [27/Jun/2019:15:19:58 -0700] "POST /hatrac/resources/publication/2019/977bd69b95d7b638462d178ce3be5185;upload?parents=true HTTP/2.0" 201 102
...
128.9.180.194 - https://auth.globus.org/1b55dedd-adf9-4c97-ba5c-e5be97a36dbd [27/Jun/2019:15:21:14 -0700] "POST /hatrac/resources/publication/2019/79f8d98c69415bdae8b3df1931c0866a;upload?parents=true HTTP/2.0" 201 102

```

Here are the relevant permissions (Animesh is only in the isrd-testers group mentioned above; I'm in https://auth.globus.org/af0b4010-5b75-11e6-9575-22000aef184d but not isrd-testers):

```
rbk-dev::laura[~] deriva-hatrac-cli --host dev.rebuildingakidney.org getacl /hatrac/resources
owner:
  https://auth.globus.org/34ef60a0-1c59-11e6-8854-279c6c8d47b2
  https://auth.globus.org/af0b4010-5b75-11e6-9575-22000aef184d
  https://auth.globus.org/a4e03698-d274-11e5-9a48-8b6f49eb5587
create:
subtree-owner:
  https://auth.globus.org/34ef60a0-1c59-11e6-8854-279c6c8d47b2
  https://auth.globus.org/9d596ac6-22b9-11e6-b519-22000aef184d
  https://auth.globus.org/a4e03698-d274-11e5-9a48-8b6f49eb5587
  https://www.globus.org/app/groups/af0b4010-5b75-11e6-9575-22000aef184d
subtree-create:
  https://auth.globus.org/af0b4010-5b75-11e6-9575-22000aef184d
subtree-read:
  *
subtree-update:
  https://auth.globus.org/af0b4010-5b75-11e6-9575-22000aef184d
rbk-dev::laura[~] deriva-hatrac-cli --host dev.rebuildingakidney.org getacl /hatrac/resources/publication
owner:
  https://auth.globus.org/a4e03698-d274-11e5-9a48-8b6f49eb5587
create:
subtree-owner:
subtree-create:
subtree-read:
subtree-update:
rbk-dev::laura[~] deriva-hatrac-cli --host dev.rebuildingakidney.org getacl /hatrac/resources/publication/2019
owner:
  https://auth.globus.org/a4e03698-d274-11e5-9a48-8b6f49eb5587
create:
subtree-owner:
subtree-create:
subtree-read:
subtree-update:
```

**Comment by karlcz** [comment]
This may be a documentation flaw or a design flaw, depending on how
you look at it.

I believe that the subtree-owner ACL of a namespace grants you
ownership on descendents but not on the namespace containing the
ACL. In other words, to grant isrd-testers ownership rights on the
/resources namespace, you need to add them to its owner ACL as well.

So, your ACLs give the isrd-testers group ownership rights on
sub-namespaces /resources/** (if they exist). Such a subtree
permission does not give you rights to create children of /resources
that do not already exist. The policy enforcement for creation is
checked at the existing parent node.

Based on the serial ids, I'm pretty sure /resources/publication did
not exist at the beginning of this test sequence. These nodes were
created in order with sequentially assigned serial IDs:

   /resources/publication
   /resources/publication/2019
   /resources/publication/2019/977bd69b95d7b638462d178ce3be5185

which I believe is the successful upload you performed.

During his initial attempt, the isrd-testers group would not have had
permission to create the missing /resources/publication, since they
have no ownership nor creation rights granted on the /resources
namespace itself.  Once those existed, he did now have ownership
rights on the /resources/publication/2019 namespace and could create
his own new object underneath.

**Comment by ljpearlman** [comment]
I see (and yes, /resources/publication was something new that Animesh was trying to create).

**Comment by karlcz** [comment]
I decided to fix the documentation rather than change the existing enforcement behavior. See the commit log for more detail.
